CC = gcc
CFLAGS = -Wall -mno-ms-bitfields
PROGS = mass-storage

all:	${PROGS}

mass-storage:	usbip.c mass-storage.c 
		${CC} ${CFLAGS} usbip.c -c 
		${CC} ${CFLAGS} usbip.o mass-storage.c -o mass-storage -lws2_32

clean:
		rm -f ${PROGS} *.o *.out *.exe
